rot90:
  _target_: src.transforms.Rotate90_3D
  k: 1
  spatial_axes: [1, 2]
rot180:
  _target_: src.transforms.Rotate90_3D
  k: 2
  spatial_axes: [1, 2]
rot270:
  _target_: src.transforms.Rotate90_3D
  k: 3
  spatial_axes: [1, 2]
