train:
  _target_: src.datasets.VesuviusDataset
  part: 'train'
  val_size: 0.1
  override: False
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.VesuviusDataset
  part: 'val'
  val_size: 0.1
  override: False
  instance_transforms: ${transforms.instance_transforms.inference}
