train:
  _target_: src.datasets.VesuviusDataset
  part: 'train'
  val_size: 0.1
  override: False
  pseudotarget_path: "data/pseudotargets"
  mix_target_with_ps: True
  instance_transforms: ${instance_transforms.train}
val:
  _target_: src.datasets.VesuviusDataset
  part: 'val'
  val_size: 0.1
  override: False
  instance_transforms: ${instance_transforms.inference}
