train:
  shift_intensity:
    _target_: src.transforms.RandShiftIntensity3D
    offsets: 0.10
    prob: 0.5
  flip1:
    _target_: src.transforms.RandFlip3D
    spatial_axis: 0 # D
    prob: 0.5
  flip2:
    _target_: src.transforms.RandFlip3D
    spatial_axis: 1 # H
    prob: 0.5
  flip3:
    _target_: src.transforms.RandFlip3D
    spatial_axis: 2 # W
    prob: 0.5
  rot90:
    _target_: src.transforms.RandRotate90_3D
    prob: 0.4
    possible_k: [1, 3]
    spatial_axes: [1, 2] # H W
  elastic_deformation:
    _target_: src.transforms.ElasticDeformation
    prob: 0.5
    sigma: 9.0
    alpha_x: 10.0
    alpha_y: 10.0
    alpha_z: 5.0
  z_drop:
    _target_: src.transforms.ZDrop3D
    prob: 0.25
    fill_mode: 'zero'
    num_blocks: [1, 3]
    block_size: [5, 20]
  cutout3d:
    _target_: src.transforms.Cutout3D
    prob: 0.25
    holes: [2, 5]
    depth: [4, 12]
    height: [24, 64]
    width: [24, 64]
    volume_fill_mode: "null"
    mask_fill_mode: "unlabeled"

inference: null
