_target_: src.loss.nnUnetLoss
base_loss:
  _target_: src.loss.BaseLoss
  num_classes: 2
  ce_weight: 1.0
  cld_weight: 0.5
  dice_weight: 1.0
  fp_weight: 0.3
  eps: 1e-7
  cld_calc_gt_skel: False
  cld_smooth_pred_skel: True
  cld_smooth_mask_skel: True
  cld_sigma: 0.8
  cld_use_downsampling: False
  cld_use_hard_diff: True
  cld_use_fast_hard: True
  cld_warmup_steps: 5000
  cld_eps: 1e-5
  cld_use_clipping: True  # clip = denominator min value
  cld_clip_value: 1.0
  cld_iterations: 1
ds_weights: null
