_target_: src.loss.SSLnnUnetLoss
base_loss:
  _target_: src.loss.MAEStructContrastiveLoss
  loss_struct:
    _target_: src.loss.TVcldMSELoss
    mse_weight: 0.5
    sskel_weight: 0.3
    tv_weight: 0.05
    cldice_use_downsampling: True
    cldice_use_blur: False
    cldice_sigma: 1.0
    cldice_iterations: 5
    tv_reduction: "mean"
  loss_contrastive:
    _target_: src.loss.BaseLossDictWrapper
    loss:
      _target_: src.loss.base_losses.InfoNCELoss
      encoding_dim: 128
      queue_size: 4096
      tau: 0.2
    name: 'infonce_loss'
  struct_weight: 1.0
  contrastive_weight: 0.2
ds_weights: null
