train:
  volume:
    _target_: src.transforms.RandShiftIntensity3D
    offsets: 0.10
    prob: 0.5
  volume@gt_mask:
    _target_: src.model.DictSequential
    _args_:
      - _target_: src.transforms.RandSpatialCrop3D
        size: [160, 160, 160]
      - _target_: src.transforms.RandFlip3D
        spatial_axis: 1 # D
        prob: 0.5
      - _target_: src.transforms.RandFlip3D
        spatial_axis: 2 # H
        prob: 0.5
      - _target_: src.transforms.RandFlip3D
        spatial_axis: 3 # W
        prob: 0.5
      - _target_: src.transforms.RandRotate90_3D
        prob: 0.4
        max_k: 3
        spatial_axes: [1, 2] # D H

inference: null

postprocess:
  outputs:
    _target_: src.transforms.PostProcess
    T_low: 0.50
    T_high: 0.90
    z_radius: 1
    xy_radius: 0
    dust_min_size: 100
