_target_: src.model.SlidingWindowWrapper
model:
  _target_: src.model.Ensemble
  ensemble_type: probs # probs | logits
  model_types: [residualunet, residualunet]
  weights_paths: [models/resunet_seed42.pth, models/resunet_seed73.pth]
roi_size: [160, 160, 160]
sw_batch_size: 1
overlap: 0.5
mode: 'gaussian'
