_target_: src.model.SlidingWindowWrapper
model:
  _target_: src.model.FPNDetector
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  features_per_stage: [32, 64, 128, 256, 320, 320]
  strides: [[1, 1, 1],[2, 2, 2],[2, 2, 2],[2, 2, 2],[2, 2, 2],[2, 2, 2]]
  n_blocks_per_stage: [1, 3, 4, 6, 6, 6]
  kernel_size: [3, 3, 3]
  fpn_channels: 96
  norm: instance
  act: leaky_relu
  conv_bias: true
  fuse_conv_kernel_size: [3, 3, 3]
roi_size: [160, 160, 160]
sw_batch_size: 1
overlap: 0.5
mode: 'gaussian'
