defaults:
  - model: transunet
  - writer: wandb
  - metrics: example
  - datasets: default
  - dataloader: default
  - transforms: main
  - loss: skeleton_dice_loss
  - optimizer: adamw
  - scheduler: cosine_annealing
  - _self_

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["volume", "gt_mask", "gt_skel"]
  resume_from: null
  from_pretrained: "models/250epochs.pth"
  device: auto
  override: False
  monitor: "max test_MulticlassAccuracy"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
