defaults:
  - model: segresnet
  - writer: wandb
  - metrics: empty
  - datasets: default
  - dataloader: debug
  - transforms: debug
  - loss: dice_loss
  - optimizer: adamw
  - lr_scheduler: warmup_cosine
  - _self_

trainer:
  log_step: 1
  n_epochs: 1
  epoch_len: 3
  device_tensors: ["volume", "gt_mask"]
  resume_from: null
  from_pretrained: null
  device: auto
  override: True
  monitor: "off"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved_debug"
  seed: 1
