defaults:
  - model: segresnet
  - metrics: empty
  - datasets: test
  - dataloader: default
  - transforms: main
  - tta_transforms: flips
  - _self_
inferencer:
  device_tensors: ["volume"]
  device: auto
  save_path: "submission_dir"
  seed: 1
  from_pretrained: "saved/segresnet-4bs/checkpoint-epoch100.pth"
