defaults:
  - model: inference-segresnet
  - metrics: empty
  - datasets: test
  - dataloader: default
  - transforms: main
  - _self_
inferencer:
  device_tensors: ["volume"]
  device: auto
  save_path: "submission_dir"
  seed: 1
  from_pretrained: "saved/baseline/checkpoint-epoch20.pth"
