defaults:
  - model: segresnet
  - writer: wandb
  - metrics: main
  - datasets: default
  - dataloader: default
  - batch_transforms: main
  - instance_transforms: main
  - loss: skeleton_dice_ce_fp_loss
  - optimizer: adamw
  - lr_scheduler: warmup_cosine
  - _self_

trainer:
  log_step: 10
  n_epochs: 50
  epoch_len: 1000
  device_tensors: ["volume", "gt_mask", "gt_skel"]
  resume_from: null
  from_pretrained: null
  device: auto
  override: False
  monitor: "min val_loss"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
  log_batch_plots: False
  view_3d_online: False
