defaults:
  - model: segresnet
  - metrics: leaderboard
  - datasets: only_val
  - dataloader: default
  - transforms: main
  - tta_transforms: empty
  - _self_
inferencer:
  device_tensors: ["volume"]
  device: auto
  seed: 1
  from_pretrained: "models/elastic.pth"
