defaults:
  - model: nnunet
  - metrics: leaderboard
  - datasets: only_val
  - dataloader: default
  - batch_transforms: main
  - instance_transforms: main
  - postprocess_transforms: empty
  - tta_transforms: empty
  - _self_
inferencer:
  device_tensors: ["volume"]
  device: auto
  seed: 1
  use_amp: False
  amp_dtype: "bfloat16"
  from_pretrained: "models/nnunet-elastic.pth"
