train:
  to_torch:
    _target_: src.transforms.ToTorch
  scale_intensity:
    _target_: src.transforms.ScaleIntensityRange
    a_min: 0
    a_max: 255
    b_min: 0
    b_max: 1
    clip: False
  sem1_copy:
    _target_: src.transforms.VolumeCopy
    name: 'volume_sem1'
  sem2_copy:
    _target_: src.transforms.VolumeCopy
    name: 'volume_sem2'
  struct_copy:
    _target_: src.transforms.VolumeCopy
    name: 'volume_struct'

  contrastive:
    gamma:
      _target_: src.transforms.RandomInstanceGammaShift3D
      prob: 0.5
      gamma_range: [0.9, 1.1]
    contrast:
      _target_: src.transforms.RandomContrast3D
      prob: 0.5
      contrast_range: [0.9, 1.1]
    normalize:
      _target_: src.transforms.Normalize3D
      mean: 0.326182128354465
      std: 0.166721404805906

  struct:
    gamma:
      _target_: src.transforms.RandomInstanceGammaShift3D
      prob: 0.5
      gamma_range: [0.9, 1.1]
    contrast:
      _target_: src.transforms.RandomContrast3D
      prob: 0.5
      contrast_range: [0.9, 1.1]
    normalize:
      _target_: src.transforms.Normalize3D
      mean: 0.326182128354465
      std: 0.166721404805906

  normalize:
    _target_: src.transforms.Normalize3D
    mean: 0.326182128354465
    std: 0.166721404805906

inference: null
