train:
  volume:
    _target_: src.transforms.ScaleIntensityRange
    a_min: 0
    a_max: 255
    clip: True

inference:
  volume:
    _target_: src.transforms.ScaleIntensityRange
    a_min: 0
    a_max: 255
    clip: True
