train:
  zoom:
    _target_: src.transforms.RandInstanceZoom3D
    prob: 0.4
    zoom_range_x: [0.9, 1.1]
    zoom_range_y: [0.9, 1.1]
    zoom_range_z: [0.95, 1.05]
  crop:
    _target_: src.transforms.RandSpatialCrop3D
    size: [160, 160, 160]
  small_rotate:
    _target_: src.transforms.RandInstanceSmallRotate3D
    prob: 0.3
    angle_x_range: [-5, 5]
    angle_y_range: [-5, 5]
    angle_z_range: [-10, 10]
  skeletonize:
    _target_: src.transforms.Skeletonize # skeletonize must be after crop
  to_torch:
    _target_: src.transforms.ToTorch # to_torch must be after skeletonize
  scale_intensity:
    _target_: src.transforms.ScaleIntensityRange
    a_min: 0
    a_max: 255
    b_min: 0
    b_max: 1
    clip: False
  gamma:
    _target_: src.transforms.RandomInstanceGammaShift3D
    prob: 0.3
    gamma_range: [0.95, 1.05]
  contrast:
    _target_: src.transforms.RandomContrast3D
    prob: 0.3
    contrast_range: [0.95, 1.05]
  normalize:
    _target_: src.transforms.Normalize3D
    mean: 0.326182128354465
    std: 0.166721404805906

inference:
  skeletonize:
    _target_: src.transforms.Skeletonize # skeletonize must be after crop
  to_torch:
    _target_: src.transforms.ToTorch # to_torch must be after skeletonize
  scale_intensity:
    _target_: src.transforms.ScaleIntensityRange
    a_min: 0
    a_max: 255
    b_min: 0
    b_max: 1
    clip: False
  normalize:
    _target_: src.transforms.Normalize3D
    mean: 0.326182128354465
    std: 0.166721404805906
